### DISCUSSION TITLE
Adjust Polling Status Description

### DISCUSSION THREAD

**Discussion by EPiSKiNG** [BigThunderSR/onstar2mqtt#556] [Ideas]
Just a quick thought I had about the Polling Status.  Was thinking it might be a good idea to change the polling status to a status of "Hibernating" when the response from Onstar is as below:

> After your engine is turned off, the vehicle will respond to about 4 - 5 requests before going into a type of hibernation mode and will not respond to requests or commands until the engine is started up again. If your engine has been off for a while, you may still not be able to get any data from the vehicle or run commands even if it is your first attempt at trying to pull data from your vehicle after the engine was turned off.
> Note: You will see an error of "Unable to establish packet session to the vehicle" when this occurs.

This way, we can monitor the polling status with more detail.

Thanks!

**Comment by BigThunderSR** [comment]
Parsing through the logs that come from the API is a nightmare to say the least because of how the API is implemented and is not something I want to undertake at this point. I have made the correlation based on my personal findings that if you get a 200 response code, it is most often because the vehicle went into hibernation. Home Assistant makes it really easy for you to map the status code that I already expose in HA to whatever verbal state you want by using a template sensor. Here's an example:

```yaml
template:
  - sensor:
      - name: "Car Hibernation Status"
        state: >
          {{ 'Hibernating' if (states('sensor.myvehicle_polling_status_code') | int == 200) else 'Not Hibernating' }}
```
> Substitute "myvehicle_polling_status_code" with your specific sensor name
