### ISSUE TITLE
Fails on startup with 400 bad request - OnStarJS keys expired - UPDATE: New version with alternate access method now available

### ISSUE THREAD

**Issue by CamSoper** [BigThunderSR/onstar2mqtt#333]
Has been solid for months. Problem started today. I pulled latest, no change.

## Output

**Attached as *logs.txt*
[logs.txt](https://github.com/user-attachments/files/17511259/logs.txt)
**

## docker-compose.yml

```yml
version: '3'
services:
  onstar2mqtt:
    container_name: onstar2mqtt
    # image: michaelwoods/onstar2mqtt
    # image: bigthundersr/onstar2mqtt:latest
    image: ghcr.io/bigthundersr/onstar2mqtt
    restart: unless-stopped
    env_file:
      - ./onstar2mqtt.env
    environment:
    - ONSTAR_DEVICEID=<snip>
    - ONSTAR_VIN=<snip>
    - MQTT_HOST=<snip>
```

## onstar2mqtt.env

```
ONSTAR_USERNAME=<nope>@outlook.com
ONSTAR_PASSWORD=<nope>
ONSTAR_PIN=<also nope>
MQTT_USERNAME=<mqttnope>
MQTT_PASSWORD=<further nope>
```
