### ISSUE TITLE
[Issue]: EV Temperature sensor not available

### ISSUE THREAD

**Issue by niravjdn** [BigThunderSR/onstar2mqtt#439]
### Describe the Issue

Hi,

I'm trying to use default dashboard which is mentioned in repo in md file but I am not able to get below sensors available to be used, are they not supported anymore?

```
 - type: 'custom:mini-graph-card'
        entities:
          - entity: sensor.<vehicle_name>_ambient_air_temperature
            name: Ambient
          - entity: sensor.<vehicle_name>_hybrid_battery_minimum_temperature
            name: Battery
          - entity: sensor.kewr_daynight_temperature
            name: Outdoor
        name: Temperature
        hours_to_show: 24
        points_per_hour: 1
        line_width: 2
```

### Type of Issue

Bug

### To Reproduce

Try to us this sensors by adding them to config or you can use default yaml shown in HA-MQTT.md

### Expected Behavior

Expected behaviour is that these sensors should be available.

### Screenshots

![Image](https://github.com/user-attachments/assets/f8fb75a3-43fa-4346-a0b4-ae4c0185b98e)

### Operating System

Docker

### Node.js Version

Runnig docker image

### npm Version

based on docker

### Other Environment Details

NA
